// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type HistoricKlineData struct {
	Opentime int     `json:"opentime"`
	Coins    []*Ohlc `json:"coins"`
}

type HistoricPrices struct {
	Pair      []*Pair `json:"Pair,omitempty"`
	Timestamp int     `json:"Timestamp"`
}

type Mutation struct {
}

type NewHistoricKlineDataInput struct {
	Opentime int          `json:"Opentime"`
	Coins    []*OHLCInput `json:"Coins"`
}

type NewHistoricPriceInput struct {
	Pairs     []*PairInput `json:"pairs"`
	Timestamp int          `json:"Timestamp"`
}

type Ohlc struct {
	OpenPrice   string `json:"OpenPrice"`
	HighPrice   string `json:"HighPrice"`
	LowPrice    string `json:"LowPrice"`
	ClosePrice  string `json:"ClosePrice"`
	TradeVolume string `json:"TradeVolume"`
	Symbol      string `json:"Symbol"`
}

type OHLCInput struct {
	OpenPrice   string `json:"OpenPrice"`
	HighPrice   string `json:"HighPrice"`
	LowPrice    string `json:"LowPrice"`
	ClosePrice  string `json:"ClosePrice"`
	TradeVolume string `json:"TradeVolume"`
	Symbol      string `json:"Symbol"`
}

type Pair struct {
	Symbol string `json:"Symbol"`
	Price  string `json:"Price"`
}

type PairInput struct {
	Symbol string `json:"Symbol"`
	Price  string `json:"Price"`
}

type Query struct {
}
