version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - gotrading
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=barry@scalpelhound.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    depends_on:
      - nginx-proxy
    networks:
      - gotrading
    restart: always




  database:
    image: ${MONGODB_IMAGE}
    container_name: database
    restart: always
    mem_limit: 512m
    ports:
      - "27017:27017"
    env_file: .env
    networks:
      - gotrading
    volumes:
      - database-data:/data/db

  cbm-api:
    image: ${RESOLVERS_IMAGE}
    ports:
      - "8080:8080"
    env_file: 
      - .env
    depends_on:
      - database
    networks:
      - gotrading
    

  microservices:
    image: ${MICROSERVICES_IMAGE}
    env_file:
      - .env
    depends_on:
      - cbm-api
    networks:
      - gotrading


  frontend:
    image: ${FRONTEND_IMAGE}
    env_file:
      - .env
    networks:
      - gotrading
    environment:
      - VIRTUAL_HOST=scalpelhound.com
      - LETSENCRYPT_HOST=scalpelhound.com
      - LETSENCRYPT_EMAIL=barry@scalpelhound.com
    expose:
      - "80"
    restart: always


networks:
  gotrading:
    name: gotrading
    driver: bridge


volumes:
  database-data:
  nats-data:
