networks:
  gotrading:
    name: gotrading
    driver: bridge

services:
  nats:
    image: ${NATS_IMAGE}
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    volumes:
      - nats-data:/data
    command: -m 8222 -js
    healthcheck:
      test: wget --spider http://127.0.0.1:8222 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 2s
    networks:
      - gotrading

  nats-cli:
    image: natsio/nats-box:latest
    depends_on:
      - nats
    entrypoint: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    environment:
      - NATS_URL=nats://nats:4222
    networks:
      - gotrading

  database:
    image: ${MONGODB_IMAGE}
    restart: always
    ports:
      - "27017:27017"
    env_file: .env
    networks:
      - gotrading
    volumes:
      - database-data:/data/db

  resolvers:
    image: ${RESOLVERS_IMAGE}
    ports:
      - "8080:8080"
    env_file: 
      - .env
    depends_on:
      - database
    networks:
      - gotrading

  microservices:
    image: ${MICROSERVICES_IMAGE}
    env_file:
      - .env
    entrypoint: ["run_priceData.sh"]
    depends_on:
      - resolvers
    networks:
      - gotrading

  frontend:
    image: ${FRONTEND_IMAGE}
    env_file:
      - .env
    networks:
      - gotrading


volumes:
  database-data:
  nats-data:
