package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"fmt"

	"cryptobotmanager.com/cbm-backend/cbm-api/graph/generated"
	"cryptobotmanager.com/cbm-backend/cbm-api/graph/model"
)

// CreateActivityReport is the resolver for the createActivityReport field.
func (r *mutationResolver) CreateActivityReport(ctx context.Context, input *model.NewActivityReport) (*model.ActivityReport, error) {
	panic(fmt.Errorf("not implemented: CreateActivityReport - createActivityReport"))
}

// CreateTradeOutcomeReport is the resolver for the createTradeOutcomeReport field.
func (r *mutationResolver) CreateTradeOutcomeReport(ctx context.Context, input *model.NewTradeOutcomeReport) (*model.TradeOutcomeReport, error) {
	panic(fmt.Errorf("not implemented: CreateTradeOutcomeReport - createTradeOutcomeReport"))
}

// DeleteOutcomeReports is the resolver for the deleteOutcomeReports field.
func (r *mutationResolver) DeleteOutcomeReports(ctx context.Context, timestamp int) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteOutcomeReports - deleteOutcomeReports"))
}

// ActivityReport is the resolver for the ActivityReport field.
func (r *queryResolver) ActivityReport(ctx context.Context, id string) (*model.ActivityReport, error) {
	panic(fmt.Errorf("not implemented: ActivityReport - ActivityReport"))
}

// ActivityReports is the resolver for the ActivityReports field.
func (r *queryResolver) ActivityReports(ctx context.Context) ([]*model.ActivityReport, error) {
	panic(fmt.Errorf("not implemented: ActivityReports - ActivityReports"))
}

// TradeOutcomeReport is the resolver for the TradeOutcomeReport field.
func (r *queryResolver) TradeOutcomeReport(ctx context.Context, id string) (*model.TradeOutcomeReport, error) {
	panic(fmt.Errorf("not implemented: TradeOutcomeReport - TradeOutcomeReport"))
}

// TradeOutcomes is the resolver for the TradeOutcomes field.
func (r *queryResolver) TradeOutcomes(ctx context.Context, botName string) ([]*model.TradeOutcomeReport, error) {
	panic(fmt.Errorf("not implemented: TradeOutcomes - TradeOutcomes"))
}

// TradeOutcomesInFocus is the resolver for the TradeOutcomesInFocus field.
func (r *queryResolver) TradeOutcomesInFocus(ctx context.Context, botName string, marketStatus string, limit *int) ([]*model.TradeOutcomeReport, error) {
	panic(fmt.Errorf("not implemented: TradeOutcomesInFocus - TradeOutcomesInFocus"))
}

// TradeOutcomeReports is the resolver for the TradeOutcomeReports field.
func (r *queryResolver) TradeOutcomeReports(ctx context.Context) ([]*model.TradeOutcomeReport, error) {
	panic(fmt.Errorf("not implemented: TradeOutcomeReports - TradeOutcomeReports"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }
