package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"fmt"

	"cryptobotmanager.com/cbm-backend/cbm-api/graph/generated"
	"cryptobotmanager.com/cbm-backend/cbm-api/graph/model"
	"github.com/rs/zerolog/log"
)

// MutationResolver implementation
func (r *mutationResolver) CreateActivityReport(ctx context.Context, input *model.NewActivityReport) (*model.ActivityReport, error) {
	return db.SaveActivityReport(input), nil
}

// CreateTradeOutcomeReport is the resolver for the createTradeOutcomeReport field.
func (r *mutationResolver) CreateTradeOutcomeReport(ctx context.Context, input *model.NewTradeOutcomeReport) (*model.TradeOutcomeReport, error) {
	return db.SaveTradeOutcomeReport(input), nil
}

// DeleteOutcomeReports is the resolver for the deleteOutcomeReports field.
func (r *mutationResolver) DeleteOutcomeReports(ctx context.Context, timestamp int) (bool, error) {
	// Assuming db is an instance of your DB type
	success, err := db.DeleteTradeOutcomeReport(ctx, timestamp)
	if err != nil {
		log.Error().Err(err).Msg("Error deleting trade outcome:")
		return false, err // Return a boolean value, not a pointer to a boolean
	}

	return success, nil
}

// UpsertSymbolStats is the resolver for the upsertSymbolStats field.
func (r *mutationResolver) UpsertSymbolStats(ctx context.Context, input *model.UpsertSymbolStatsInput) (*model.SymbolStats, error) {
	return db.UpsertSymbolStats(input), nil
}

// DeleteSymbolStats is the resolver for the deleteSymbolStats field.
func (r *mutationResolver) DeleteSymbolStats(ctx context.Context, symbol string) (bool, error) {
	success, err := db.DeleteSymbolStats(ctx, symbol)
	return success, err
}

// ReadActivityReport is the resolver for the readActivityReport field.
func (r *queryResolver) ReadActivityReport(ctx context.Context, id string) (*model.ActivityReport, error) {
	panic(fmt.Errorf("not implemented: ReadActivityReport - readActivityReport"))
}

// ReadAllActivityReports is the resolver for the readAllActivityReports field.
func (r *queryResolver) ReadAllActivityReports(ctx context.Context) ([]*model.ActivityReport, error) {
	panic(fmt.Errorf("not implemented: ReadAllActivityReports - readAllActivityReports"))
}

// ReadTradeOutcomeReport is the resolver for the readTradeOutcomeReport field.
func (r *queryResolver) ReadTradeOutcomeReport(ctx context.Context, id string) (*model.TradeOutcomeReport, error) {
	panic(fmt.Errorf("not implemented: ReadTradeOutcomeReport - readTradeOutcomeReport"))
}

// ReadTradeOutcomes is the resolver for the readTradeOutcomes field.
func (r *queryResolver) ReadTradeOutcomes(ctx context.Context, botName string) ([]*model.TradeOutcomeReport, error) {
	panic(fmt.Errorf("not implemented: ReadTradeOutcomes - readTradeOutcomes"))
}

// ReadTradeOutcomesInFocus is the resolver for the readTradeOutcomesInFocus field.
func (r *queryResolver) ReadTradeOutcomesInFocus(ctx context.Context, botName string, marketStatus string, limit *int) ([]*model.TradeOutcomeReport, error) {
	panic(fmt.Errorf("not implemented: ReadTradeOutcomesInFocus - readTradeOutcomesInFocus"))
}

// ReadAllTradeOutcomeReports is the resolver for the readAllTradeOutcomeReports field.
func (r *queryResolver) ReadAllTradeOutcomeReports(ctx context.Context) ([]*model.TradeOutcomeReport, error) {
	panic(fmt.Errorf("not implemented: ReadAllTradeOutcomeReports - readAllTradeOutcomeReports"))
}

// ReadAllSymbolStatsReports is the resolver for the readAllSymbolStatsReports field.
func (r *queryResolver) ReadAllSymbolStatsReports(ctx context.Context) ([]*model.SymbolStats, error) {
	panic(fmt.Errorf("not implemented: ReadAllSymbolStatsReports - readAllSymbolStatsReports"))
}

// ReadSymbolStatsBySymbol is the resolver for the readSymbolStatsBySymbol field.
func (r *queryResolver) ReadSymbolStatsBySymbol(ctx context.Context, symbol string) (*model.SymbolStats, error) {
	panic(fmt.Errorf("not implemented: ReadSymbolStatsBySymbol - readSymbolStatsBySymbol"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) ActivityReport(ctx context.Context, id string) (*model.ActivityReport, error) {
	return db.FindActivityReportByID(id), nil
}
func (r *queryResolver) ActivityReports(ctx context.Context) ([]*model.ActivityReport, error) {
	return db.AllActivityReports(), nil
}
func (r *queryResolver) TradeOutcomeReport(ctx context.Context, id string) (*model.TradeOutcomeReport, error) {
	return db.FindTradeOutcomeReportByID(id), nil
}
func (r *queryResolver) TradeOutcomes(ctx context.Context, botName string) ([]*model.TradeOutcomeReport, error) {
	return db.TradeOutcomeReportsByBotName(ctx, botName)
}
func (r *queryResolver) TradeOutcomesInFocus(ctx context.Context, botName string, marketStatus string, limit *int) ([]*model.TradeOutcomeReport, error) {
	return db.TradeOutcomeReportsByBotNameAndMarketStatus(ctx, botName, marketStatus, *limit)
}
func (r *queryResolver) TradeOutcomeReports(ctx context.Context) ([]*model.TradeOutcomeReport, error) {
	return db.AllTradeOutcomeReports(), nil
}
func (r *queryResolver) SymbolStatsReports(ctx context.Context) ([]*model.SymbolStats, error) {
	return db.AllSymbolStats(), nil
}
func (r *queryResolver) SymbolStatsBySymbol(ctx context.Context, symbol string) (*model.SymbolStats, error) {
	return db.FindSymbolStatsBySymbol(ctx, symbol), nil
}
*/
