package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"

	"cryptobotmanager.com/cbm-backend/cbm-api/graph/model"
	"github.com/rs/zerolog/log"
)

// UpsertSymbolStats is the resolver for the upsertSymbolStats field.
func (r *mutationResolver) UpsertSymbolStats(ctx context.Context, input *model.UpsertSymbolStatsInput) (*model.SymbolStats, error) {
	return db.UpsertSymbolStats(input), nil
}

// DeleteSymbolStats is the resolver for the deleteSymbolStats field.
func (r *mutationResolver) DeleteSymbolStats(ctx context.Context, symbol string) (bool, error) {
	success, err := db.DeleteSymbolStats(ctx, symbol)
	return success, err
}

// CreateHistoricTickerStats is the resolver for the createHistoricTickerStats field.
func (r *mutationResolver) CreateHistoricTickerStats(ctx context.Context, input model.NewHistoricTickerStatsInput) ([]*model.HistoricTickerStats, error) {
	// Assuming you want to save multiple HistoricKlineData in the input
	insertedHistoricKlineData, err := db.SaveHistoricTickerStats(input)
	if err != nil {
		return nil, err
	}

	// Assuming you want to return the insertedHistoricKlineData and the timestamp
	return insertedHistoricKlineData, nil
}

// DeleteHistoricTickerStats is the resolver for the deleteHistoricTickerStats field.
func (r *mutationResolver) DeleteHistoricTickerStats(ctx context.Context, timestamp int) (bool, error) {
	err := db.DeleteHistoricTickerStatsByTimestamp(ctx, timestamp)

	if err != nil {
		log.Error().Err(err).Msg("Error getting Unique Timestamp Count")
		return false, err
	}

	return true, nil
}

// SymbolStatsReports is the resolver for the SymbolStatsReports field.
func (r *queryResolver) SymbolStatsReports(ctx context.Context) ([]*model.SymbolStats, error) {
	return db.AllSymbolStats(), nil
}

// SymbolStatsBySymbol is the resolver for the SymbolStatsBySymbol field.
func (r *queryResolver) SymbolStatsBySymbol(ctx context.Context, symbol string) (*model.SymbolStats, error) {
	return db.FindSymbolStatsBySymbol(ctx, symbol), nil
}

// GetHistoricTickerStatsAtTimestamp is the resolver for the getHistoricTickerStatsAtTimestamp field.
func (r *queryResolver) GetHistoricTickerStatsAtTimestamp(ctx context.Context, timestamp int) ([]*model.HistoricTickerStats, error) {
	log.Info().Msgf("Fetching historic ticker stats at Timestamp: %d", timestamp)

	historicTickerStats, err := db.HistoricTickerStatsAtTimestamp(timestamp)
	if err != nil {
		log.Error().Err(err).Msg("Error getting historic ticker stats at timestamp")
		return nil, err
	}

	// Convert slice of model.HistoricTickerStats to slice of *model.HistoricTickerStats
	var result []*model.HistoricTickerStats
	for i := range historicTickerStats {
		result = append(result, &historicTickerStats[i])
	}

	log.Info().Msgf("Retrieved ticker stats: %+v", historicTickerStats)

	// Return the slice of pointers to historic ticker stats
	return result, nil
}

// GetTickerStatsBySymbol is the resolver for the getTickerStatsBySymbol field.
func (r *queryResolver) GetTickerStatsBySymbol(ctx context.Context, symbol string, limit *int) ([]*model.TickerStats, error) {
	log.Info().
		Str("symbol", symbol).
		Int("limit", func() int {
			if limit != nil {
				return *limit
			}
			return 0
		}()).
		Msg("GetTickerStatsBySymbol called")

	l := 0
	if limit != nil {
		l = *limit
	}

	tickerStats, err := db.TickerStatsBySymbol(symbol, l)
	if err != nil {
		log.Error().Err(err).Msg("Error getting ticker stats by symbol")
		return nil, err
	}

	return tickerStats, nil // already []*model.TickerStats
}
