// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package graph

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// CreateActivityReportCreateActivityReport includes the requested fields of the GraphQL type ActivityReport.
type CreateActivityReportCreateActivityReport struct {
	Id             string  `json:"_id"`
	Timestamp      int     `json:"Timestamp"`
	Qty            int     `json:"Qty"`
	AvgGain        float64 `json:"AvgGain"`
	TopAGain       float64 `json:"TopAGain"`
	TopBGain       float64 `json:"TopBGain"`
	TopCGain       float64 `json:"TopCGain"`
	FearGreedIndex int     `json:"FearGreedIndex"`
}

// GetId returns CreateActivityReportCreateActivityReport.Id, and is useful for accessing the field via an interface.
func (v *CreateActivityReportCreateActivityReport) GetId() string { return v.Id }

// GetTimestamp returns CreateActivityReportCreateActivityReport.Timestamp, and is useful for accessing the field via an interface.
func (v *CreateActivityReportCreateActivityReport) GetTimestamp() int { return v.Timestamp }

// GetQty returns CreateActivityReportCreateActivityReport.Qty, and is useful for accessing the field via an interface.
func (v *CreateActivityReportCreateActivityReport) GetQty() int { return v.Qty }

// GetAvgGain returns CreateActivityReportCreateActivityReport.AvgGain, and is useful for accessing the field via an interface.
func (v *CreateActivityReportCreateActivityReport) GetAvgGain() float64 { return v.AvgGain }

// GetTopAGain returns CreateActivityReportCreateActivityReport.TopAGain, and is useful for accessing the field via an interface.
func (v *CreateActivityReportCreateActivityReport) GetTopAGain() float64 { return v.TopAGain }

// GetTopBGain returns CreateActivityReportCreateActivityReport.TopBGain, and is useful for accessing the field via an interface.
func (v *CreateActivityReportCreateActivityReport) GetTopBGain() float64 { return v.TopBGain }

// GetTopCGain returns CreateActivityReportCreateActivityReport.TopCGain, and is useful for accessing the field via an interface.
func (v *CreateActivityReportCreateActivityReport) GetTopCGain() float64 { return v.TopCGain }

// GetFearGreedIndex returns CreateActivityReportCreateActivityReport.FearGreedIndex, and is useful for accessing the field via an interface.
func (v *CreateActivityReportCreateActivityReport) GetFearGreedIndex() int { return v.FearGreedIndex }

// CreateActivityReportResponse is returned by CreateActivityReport on success.
type CreateActivityReportResponse struct {
	// Creates a new market Activity Report
	CreateActivityReport CreateActivityReportCreateActivityReport `json:"createActivityReport"`
}

// GetCreateActivityReport returns CreateActivityReportResponse.CreateActivityReport, and is useful for accessing the field via an interface.
func (v *CreateActivityReportResponse) GetCreateActivityReport() CreateActivityReportCreateActivityReport {
	return v.CreateActivityReport
}

// CreateHistoricPricesCreateHistoricPrices includes the requested fields of the GraphQL type HistoricPrices.
type CreateHistoricPricesCreateHistoricPrices struct {
	Pair []CreateHistoricPricesCreateHistoricPricesPair `json:"Pair"`
}

// GetPair returns CreateHistoricPricesCreateHistoricPrices.Pair, and is useful for accessing the field via an interface.
func (v *CreateHistoricPricesCreateHistoricPrices) GetPair() []CreateHistoricPricesCreateHistoricPricesPair {
	return v.Pair
}

// CreateHistoricPricesCreateHistoricPricesPair includes the requested fields of the GraphQL type Pair.
type CreateHistoricPricesCreateHistoricPricesPair struct {
	Symbol string `json:"Symbol"`
	Price  string `json:"Price"`
}

// GetSymbol returns CreateHistoricPricesCreateHistoricPricesPair.Symbol, and is useful for accessing the field via an interface.
func (v *CreateHistoricPricesCreateHistoricPricesPair) GetSymbol() string { return v.Symbol }

// GetPrice returns CreateHistoricPricesCreateHistoricPricesPair.Price, and is useful for accessing the field via an interface.
func (v *CreateHistoricPricesCreateHistoricPricesPair) GetPrice() string { return v.Price }

// CreateHistoricPricesResponse is returned by CreateHistoricPrices on success.
type CreateHistoricPricesResponse struct {
	// Creates an array of Historic Price pairs
	CreateHistoricPrices []CreateHistoricPricesCreateHistoricPrices `json:"createHistoricPrices"`
}

// GetCreateHistoricPrices returns CreateHistoricPricesResponse.CreateHistoricPrices, and is useful for accessing the field via an interface.
func (v *CreateHistoricPricesResponse) GetCreateHistoricPrices() []CreateHistoricPricesCreateHistoricPrices {
	return v.CreateHistoricPrices
}

// CreateHistoricTickerStatsCreateHistoricTickerStats includes the requested fields of the GraphQL type HistoricTickerStats.
type CreateHistoricTickerStatsCreateHistoricTickerStats struct {
	Timestamp int                                                                  `json:"Timestamp"`
	Stats     []CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats `json:"Stats"`
	CreatedAt string                                                               `json:"CreatedAt"`
}

// GetTimestamp returns CreateHistoricTickerStatsCreateHistoricTickerStats.Timestamp, and is useful for accessing the field via an interface.
func (v *CreateHistoricTickerStatsCreateHistoricTickerStats) GetTimestamp() int { return v.Timestamp }

// GetStats returns CreateHistoricTickerStatsCreateHistoricTickerStats.Stats, and is useful for accessing the field via an interface.
func (v *CreateHistoricTickerStatsCreateHistoricTickerStats) GetStats() []CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats {
	return v.Stats
}

// GetCreatedAt returns CreateHistoricTickerStatsCreateHistoricTickerStats.CreatedAt, and is useful for accessing the field via an interface.
func (v *CreateHistoricTickerStatsCreateHistoricTickerStats) GetCreatedAt() string {
	return v.CreatedAt
}

// CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats includes the requested fields of the GraphQL type TickerStats.
type CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats struct {
	Symbol            string `json:"Symbol"`
	PriceChange       string `json:"PriceChange"`
	PriceChangePct    string `json:"PriceChangePct"`
	QuoteVolume       string `json:"QuoteVolume"`
	Volume            string `json:"Volume"`
	TradeCount        int    `json:"TradeCount"`
	HighPrice         string `json:"HighPrice"`
	LowPrice          string `json:"LowPrice"`
	LastPrice         string `json:"LastPrice"`
	LiquidityEstimate string `json:"LiquidityEstimate"`
}

// GetSymbol returns CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats.Symbol, and is useful for accessing the field via an interface.
func (v *CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats) GetSymbol() string {
	return v.Symbol
}

// GetPriceChange returns CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats.PriceChange, and is useful for accessing the field via an interface.
func (v *CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats) GetPriceChange() string {
	return v.PriceChange
}

// GetPriceChangePct returns CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats.PriceChangePct, and is useful for accessing the field via an interface.
func (v *CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats) GetPriceChangePct() string {
	return v.PriceChangePct
}

// GetQuoteVolume returns CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats.QuoteVolume, and is useful for accessing the field via an interface.
func (v *CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats) GetQuoteVolume() string {
	return v.QuoteVolume
}

// GetVolume returns CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats.Volume, and is useful for accessing the field via an interface.
func (v *CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats) GetVolume() string {
	return v.Volume
}

// GetTradeCount returns CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats.TradeCount, and is useful for accessing the field via an interface.
func (v *CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats) GetTradeCount() int {
	return v.TradeCount
}

// GetHighPrice returns CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats.HighPrice, and is useful for accessing the field via an interface.
func (v *CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats) GetHighPrice() string {
	return v.HighPrice
}

// GetLowPrice returns CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats.LowPrice, and is useful for accessing the field via an interface.
func (v *CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats) GetLowPrice() string {
	return v.LowPrice
}

// GetLastPrice returns CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats.LastPrice, and is useful for accessing the field via an interface.
func (v *CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats) GetLastPrice() string {
	return v.LastPrice
}

// GetLiquidityEstimate returns CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats.LiquidityEstimate, and is useful for accessing the field via an interface.
func (v *CreateHistoricTickerStatsCreateHistoricTickerStatsStatsTickerStats) GetLiquidityEstimate() string {
	return v.LiquidityEstimate
}

// CreateHistoricTickerStatsResponse is returned by CreateHistoricTickerStats on success.
type CreateHistoricTickerStatsResponse struct {
	// Creates an array of 24h Ticker Stats at a given timestamp
	CreateHistoricTickerStats []CreateHistoricTickerStatsCreateHistoricTickerStats `json:"createHistoricTickerStats"`
}

// GetCreateHistoricTickerStats returns CreateHistoricTickerStatsResponse.CreateHistoricTickerStats, and is useful for accessing the field via an interface.
func (v *CreateHistoricTickerStatsResponse) GetCreateHistoricTickerStats() []CreateHistoricTickerStatsCreateHistoricTickerStats {
	return v.CreateHistoricTickerStats
}

// CreateProjectCreateProject includes the requested fields of the GraphQL type Project.
type CreateProjectCreateProject struct {
	Id          string   `json:"id"`
	Title       string   `json:"title"`
	Sop         bool     `json:"sop"`
	Description string   `json:"description"`
	Labels      []string `json:"labels"`
	AssignedTo  string   `json:"assignedTo"`
	DueDate     string   `json:"dueDate"`
	Status      string   `json:"status"`
	CreatedAt   string   `json:"createdAt"`
	UpdatedAt   string   `json:"updatedAt"`
}

// GetId returns CreateProjectCreateProject.Id, and is useful for accessing the field via an interface.
func (v *CreateProjectCreateProject) GetId() string { return v.Id }

// GetTitle returns CreateProjectCreateProject.Title, and is useful for accessing the field via an interface.
func (v *CreateProjectCreateProject) GetTitle() string { return v.Title }

// GetSop returns CreateProjectCreateProject.Sop, and is useful for accessing the field via an interface.
func (v *CreateProjectCreateProject) GetSop() bool { return v.Sop }

// GetDescription returns CreateProjectCreateProject.Description, and is useful for accessing the field via an interface.
func (v *CreateProjectCreateProject) GetDescription() string { return v.Description }

// GetLabels returns CreateProjectCreateProject.Labels, and is useful for accessing the field via an interface.
func (v *CreateProjectCreateProject) GetLabels() []string { return v.Labels }

// GetAssignedTo returns CreateProjectCreateProject.AssignedTo, and is useful for accessing the field via an interface.
func (v *CreateProjectCreateProject) GetAssignedTo() string { return v.AssignedTo }

// GetDueDate returns CreateProjectCreateProject.DueDate, and is useful for accessing the field via an interface.
func (v *CreateProjectCreateProject) GetDueDate() string { return v.DueDate }

// GetStatus returns CreateProjectCreateProject.Status, and is useful for accessing the field via an interface.
func (v *CreateProjectCreateProject) GetStatus() string { return v.Status }

// GetCreatedAt returns CreateProjectCreateProject.CreatedAt, and is useful for accessing the field via an interface.
func (v *CreateProjectCreateProject) GetCreatedAt() string { return v.CreatedAt }

// GetUpdatedAt returns CreateProjectCreateProject.UpdatedAt, and is useful for accessing the field via an interface.
func (v *CreateProjectCreateProject) GetUpdatedAt() string { return v.UpdatedAt }

type CreateProjectInput struct {
	Title       string   `json:"title"`
	Sop         bool     `json:"sop"`
	Description string   `json:"description"`
	Labels      []string `json:"labels"`
	AssignedTo  string   `json:"assignedTo"`
	DueDate     string   `json:"dueDate"`
	Status      string   `json:"status"`
}

// GetTitle returns CreateProjectInput.Title, and is useful for accessing the field via an interface.
func (v *CreateProjectInput) GetTitle() string { return v.Title }

// GetSop returns CreateProjectInput.Sop, and is useful for accessing the field via an interface.
func (v *CreateProjectInput) GetSop() bool { return v.Sop }

// GetDescription returns CreateProjectInput.Description, and is useful for accessing the field via an interface.
func (v *CreateProjectInput) GetDescription() string { return v.Description }

// GetLabels returns CreateProjectInput.Labels, and is useful for accessing the field via an interface.
func (v *CreateProjectInput) GetLabels() []string { return v.Labels }

// GetAssignedTo returns CreateProjectInput.AssignedTo, and is useful for accessing the field via an interface.
func (v *CreateProjectInput) GetAssignedTo() string { return v.AssignedTo }

// GetDueDate returns CreateProjectInput.DueDate, and is useful for accessing the field via an interface.
func (v *CreateProjectInput) GetDueDate() string { return v.DueDate }

// GetStatus returns CreateProjectInput.Status, and is useful for accessing the field via an interface.
func (v *CreateProjectInput) GetStatus() string { return v.Status }

// CreateProjectResponse is returned by CreateProject on success.
type CreateProjectResponse struct {
	// Create a new project
	CreateProject CreateProjectCreateProject `json:"createProject"`
}

// GetCreateProject returns CreateProjectResponse.CreateProject, and is useful for accessing the field via an interface.
func (v *CreateProjectResponse) GetCreateProject() CreateProjectCreateProject { return v.CreateProject }

// CreateTaskCreateTask includes the requested fields of the GraphQL type Task.
type CreateTaskCreateTask struct {
	Id          string   `json:"id"`
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Status      string   `json:"status"`
	Labels      []string `json:"labels"`
	AssignedTo  string   `json:"assignedTo"`
	DueDate     string   `json:"dueDate"`
	DeferDate   string   `json:"deferDate"`
	Department  string   `json:"department"`
	ProjectId   string   `json:"projectId"`
	Duration    int      `json:"duration"`
	CreatedAt   string   `json:"createdAt"`
	UpdatedAt   string   `json:"updatedAt"`
}

// GetId returns CreateTaskCreateTask.Id, and is useful for accessing the field via an interface.
func (v *CreateTaskCreateTask) GetId() string { return v.Id }

// GetTitle returns CreateTaskCreateTask.Title, and is useful for accessing the field via an interface.
func (v *CreateTaskCreateTask) GetTitle() string { return v.Title }

// GetDescription returns CreateTaskCreateTask.Description, and is useful for accessing the field via an interface.
func (v *CreateTaskCreateTask) GetDescription() string { return v.Description }

// GetStatus returns CreateTaskCreateTask.Status, and is useful for accessing the field via an interface.
func (v *CreateTaskCreateTask) GetStatus() string { return v.Status }

// GetLabels returns CreateTaskCreateTask.Labels, and is useful for accessing the field via an interface.
func (v *CreateTaskCreateTask) GetLabels() []string { return v.Labels }

// GetAssignedTo returns CreateTaskCreateTask.AssignedTo, and is useful for accessing the field via an interface.
func (v *CreateTaskCreateTask) GetAssignedTo() string { return v.AssignedTo }

// GetDueDate returns CreateTaskCreateTask.DueDate, and is useful for accessing the field via an interface.
func (v *CreateTaskCreateTask) GetDueDate() string { return v.DueDate }

// GetDeferDate returns CreateTaskCreateTask.DeferDate, and is useful for accessing the field via an interface.
func (v *CreateTaskCreateTask) GetDeferDate() string { return v.DeferDate }

// GetDepartment returns CreateTaskCreateTask.Department, and is useful for accessing the field via an interface.
func (v *CreateTaskCreateTask) GetDepartment() string { return v.Department }

// GetProjectId returns CreateTaskCreateTask.ProjectId, and is useful for accessing the field via an interface.
func (v *CreateTaskCreateTask) GetProjectId() string { return v.ProjectId }

// GetDuration returns CreateTaskCreateTask.Duration, and is useful for accessing the field via an interface.
func (v *CreateTaskCreateTask) GetDuration() int { return v.Duration }

// GetCreatedAt returns CreateTaskCreateTask.CreatedAt, and is useful for accessing the field via an interface.
func (v *CreateTaskCreateTask) GetCreatedAt() string { return v.CreatedAt }

// GetUpdatedAt returns CreateTaskCreateTask.UpdatedAt, and is useful for accessing the field via an interface.
func (v *CreateTaskCreateTask) GetUpdatedAt() string { return v.UpdatedAt }

type CreateTaskInput struct {
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Status      string   `json:"status"`
	Labels      []string `json:"labels"`
	AssignedTo  string   `json:"assignedTo"`
	DueDate     string   `json:"dueDate"`
	DeferDate   string   `json:"deferDate"`
	Department  string   `json:"department"`
	ProjectId   string   `json:"projectId"`
	Duration    int      `json:"duration"`
}

// GetTitle returns CreateTaskInput.Title, and is useful for accessing the field via an interface.
func (v *CreateTaskInput) GetTitle() string { return v.Title }

// GetDescription returns CreateTaskInput.Description, and is useful for accessing the field via an interface.
func (v *CreateTaskInput) GetDescription() string { return v.Description }

// GetStatus returns CreateTaskInput.Status, and is useful for accessing the field via an interface.
func (v *CreateTaskInput) GetStatus() string { return v.Status }

// GetLabels returns CreateTaskInput.Labels, and is useful for accessing the field via an interface.
func (v *CreateTaskInput) GetLabels() []string { return v.Labels }

// GetAssignedTo returns CreateTaskInput.AssignedTo, and is useful for accessing the field via an interface.
func (v *CreateTaskInput) GetAssignedTo() string { return v.AssignedTo }

// GetDueDate returns CreateTaskInput.DueDate, and is useful for accessing the field via an interface.
func (v *CreateTaskInput) GetDueDate() string { return v.DueDate }

// GetDeferDate returns CreateTaskInput.DeferDate, and is useful for accessing the field via an interface.
func (v *CreateTaskInput) GetDeferDate() string { return v.DeferDate }

// GetDepartment returns CreateTaskInput.Department, and is useful for accessing the field via an interface.
func (v *CreateTaskInput) GetDepartment() string { return v.Department }

// GetProjectId returns CreateTaskInput.ProjectId, and is useful for accessing the field via an interface.
func (v *CreateTaskInput) GetProjectId() string { return v.ProjectId }

// GetDuration returns CreateTaskInput.Duration, and is useful for accessing the field via an interface.
func (v *CreateTaskInput) GetDuration() int { return v.Duration }

// CreateTaskResponse is returned by CreateTask on success.
type CreateTaskResponse struct {
	// Create a new task
	CreateTask CreateTaskCreateTask `json:"createTask"`
}

// GetCreateTask returns CreateTaskResponse.CreateTask, and is useful for accessing the field via an interface.
func (v *CreateTaskResponse) GetCreateTask() CreateTaskCreateTask { return v.CreateTask }

// CreateTradeOutcomeReportCreateTradeOutcomeReport includes the requested fields of the GraphQL type TradeOutcomeReport.
type CreateTradeOutcomeReportCreateTradeOutcomeReport struct {
	Id               string  `json:"_id"`
	Timestamp        int     `json:"Timestamp"`
	BotName          string  `json:"BotName"`
	PercentageChange float64 `json:"PercentageChange"`
	Balance          float64 `json:"Balance"`
	Symbol           string  `json:"Symbol"`
	Outcome          string  `json:"Outcome"`
	Fee              float64 `json:"Fee"`
	ElapsedTime      int     `json:"ElapsedTime"`
	Volume           float64 `json:"Volume"`
	FearGreedIndex   int     `json:"FearGreedIndex"`
	MarketStatus     string  `json:"MarketStatus"`
}

// GetId returns CreateTradeOutcomeReportCreateTradeOutcomeReport.Id, and is useful for accessing the field via an interface.
func (v *CreateTradeOutcomeReportCreateTradeOutcomeReport) GetId() string { return v.Id }

// GetTimestamp returns CreateTradeOutcomeReportCreateTradeOutcomeReport.Timestamp, and is useful for accessing the field via an interface.
func (v *CreateTradeOutcomeReportCreateTradeOutcomeReport) GetTimestamp() int { return v.Timestamp }

// GetBotName returns CreateTradeOutcomeReportCreateTradeOutcomeReport.BotName, and is useful for accessing the field via an interface.
func (v *CreateTradeOutcomeReportCreateTradeOutcomeReport) GetBotName() string { return v.BotName }

// GetPercentageChange returns CreateTradeOutcomeReportCreateTradeOutcomeReport.PercentageChange, and is useful for accessing the field via an interface.
func (v *CreateTradeOutcomeReportCreateTradeOutcomeReport) GetPercentageChange() float64 {
	return v.PercentageChange
}

// GetBalance returns CreateTradeOutcomeReportCreateTradeOutcomeReport.Balance, and is useful for accessing the field via an interface.
func (v *CreateTradeOutcomeReportCreateTradeOutcomeReport) GetBalance() float64 { return v.Balance }

// GetSymbol returns CreateTradeOutcomeReportCreateTradeOutcomeReport.Symbol, and is useful for accessing the field via an interface.
func (v *CreateTradeOutcomeReportCreateTradeOutcomeReport) GetSymbol() string { return v.Symbol }

// GetOutcome returns CreateTradeOutcomeReportCreateTradeOutcomeReport.Outcome, and is useful for accessing the field via an interface.
func (v *CreateTradeOutcomeReportCreateTradeOutcomeReport) GetOutcome() string { return v.Outcome }

// GetFee returns CreateTradeOutcomeReportCreateTradeOutcomeReport.Fee, and is useful for accessing the field via an interface.
func (v *CreateTradeOutcomeReportCreateTradeOutcomeReport) GetFee() float64 { return v.Fee }

// GetElapsedTime returns CreateTradeOutcomeReportCreateTradeOutcomeReport.ElapsedTime, and is useful for accessing the field via an interface.
func (v *CreateTradeOutcomeReportCreateTradeOutcomeReport) GetElapsedTime() int { return v.ElapsedTime }

// GetVolume returns CreateTradeOutcomeReportCreateTradeOutcomeReport.Volume, and is useful for accessing the field via an interface.
func (v *CreateTradeOutcomeReportCreateTradeOutcomeReport) GetVolume() float64 { return v.Volume }

// GetFearGreedIndex returns CreateTradeOutcomeReportCreateTradeOutcomeReport.FearGreedIndex, and is useful for accessing the field via an interface.
func (v *CreateTradeOutcomeReportCreateTradeOutcomeReport) GetFearGreedIndex() int {
	return v.FearGreedIndex
}

// GetMarketStatus returns CreateTradeOutcomeReportCreateTradeOutcomeReport.MarketStatus, and is useful for accessing the field via an interface.
func (v *CreateTradeOutcomeReportCreateTradeOutcomeReport) GetMarketStatus() string {
	return v.MarketStatus
}

// CreateTradeOutcomeReportResponse is returned by CreateTradeOutcomeReport on success.
type CreateTradeOutcomeReportResponse struct {
	// Creates a new Trade Outcome Report
	CreateTradeOutcomeReport CreateTradeOutcomeReportCreateTradeOutcomeReport `json:"createTradeOutcomeReport"`
}

// GetCreateTradeOutcomeReport returns CreateTradeOutcomeReportResponse.CreateTradeOutcomeReport, and is useful for accessing the field via an interface.
func (v *CreateTradeOutcomeReportResponse) GetCreateTradeOutcomeReport() CreateTradeOutcomeReportCreateTradeOutcomeReport {
	return v.CreateTradeOutcomeReport
}

// CreateUserCreateUser includes the requested fields of the GraphQL type User.
type CreateUserCreateUser struct {
	Id        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Role      string `json:"role"`
}

// GetId returns CreateUserCreateUser.Id, and is useful for accessing the field via an interface.
func (v *CreateUserCreateUser) GetId() string { return v.Id }

// GetFirstName returns CreateUserCreateUser.FirstName, and is useful for accessing the field via an interface.
func (v *CreateUserCreateUser) GetFirstName() string { return v.FirstName }

// GetLastName returns CreateUserCreateUser.LastName, and is useful for accessing the field via an interface.
func (v *CreateUserCreateUser) GetLastName() string { return v.LastName }

// GetEmail returns CreateUserCreateUser.Email, and is useful for accessing the field via an interface.
func (v *CreateUserCreateUser) GetEmail() string { return v.Email }

// GetRole returns CreateUserCreateUser.Role, and is useful for accessing the field via an interface.
func (v *CreateUserCreateUser) GetRole() string { return v.Role }

type CreateUserInput struct {
	FirstName              string `json:"firstName"`
	LastName               string `json:"lastName"`
	Email                  string `json:"email"`
	Password               string `json:"password"`
	MobileNumber           string `json:"mobileNumber"`
	Role                   string `json:"role"`
	InvitedBy              string `json:"invitedBy"`
	PreferredContactMethod string `json:"preferredContactMethod"`
}

// GetFirstName returns CreateUserInput.FirstName, and is useful for accessing the field via an interface.
func (v *CreateUserInput) GetFirstName() string { return v.FirstName }

// GetLastName returns CreateUserInput.LastName, and is useful for accessing the field via an interface.
func (v *CreateUserInput) GetLastName() string { return v.LastName }

// GetEmail returns CreateUserInput.Email, and is useful for accessing the field via an interface.
func (v *CreateUserInput) GetEmail() string { return v.Email }

// GetPassword returns CreateUserInput.Password, and is useful for accessing the field via an interface.
func (v *CreateUserInput) GetPassword() string { return v.Password }

// GetMobileNumber returns CreateUserInput.MobileNumber, and is useful for accessing the field via an interface.
func (v *CreateUserInput) GetMobileNumber() string { return v.MobileNumber }

// GetRole returns CreateUserInput.Role, and is useful for accessing the field via an interface.
func (v *CreateUserInput) GetRole() string { return v.Role }

// GetInvitedBy returns CreateUserInput.InvitedBy, and is useful for accessing the field via an interface.
func (v *CreateUserInput) GetInvitedBy() string { return v.InvitedBy }

// GetPreferredContactMethod returns CreateUserInput.PreferredContactMethod, and is useful for accessing the field via an interface.
func (v *CreateUserInput) GetPreferredContactMethod() string { return v.PreferredContactMethod }

// CreateUserResponse is returned by CreateUser on success.
type CreateUserResponse struct {
	// Creates a new user
	CreateUser CreateUserCreateUser `json:"createUser"`
}

// GetCreateUser returns CreateUserResponse.CreateUser, and is useful for accessing the field via an interface.
func (v *CreateUserResponse) GetCreateUser() CreateUserCreateUser { return v.CreateUser }

// GetAllProjectsFilterProjectsProject includes the requested fields of the GraphQL type Project.
type GetAllProjectsFilterProjectsProject struct {
	Id          string                                         `json:"id"`
	Title       string                                         `json:"title"`
	Sop         bool                                           `json:"sop"`
	Description string                                         `json:"description"`
	Labels      []string                                       `json:"labels"`
	AssignedTo  string                                         `json:"assignedTo"`
	DueDate     string                                         `json:"dueDate"`
	Status      string                                         `json:"status"`
	CreatedAt   string                                         `json:"createdAt"`
	UpdatedAt   string                                         `json:"updatedAt"`
	Tasks       []GetAllProjectsFilterProjectsProjectTasksTask `json:"tasks"`
}

// GetId returns GetAllProjectsFilterProjectsProject.Id, and is useful for accessing the field via an interface.
func (v *GetAllProjectsFilterProjectsProject) GetId() string { return v.Id }

// GetTitle returns GetAllProjectsFilterProjectsProject.Title, and is useful for accessing the field via an interface.
func (v *GetAllProjectsFilterProjectsProject) GetTitle() string { return v.Title }

// GetSop returns GetAllProjectsFilterProjectsProject.Sop, and is useful for accessing the field via an interface.
func (v *GetAllProjectsFilterProjectsProject) GetSop() bool { return v.Sop }

// GetDescription returns GetAllProjectsFilterProjectsProject.Description, and is useful for accessing the field via an interface.
func (v *GetAllProjectsFilterProjectsProject) GetDescription() string { return v.Description }

// GetLabels returns GetAllProjectsFilterProjectsProject.Labels, and is useful for accessing the field via an interface.
func (v *GetAllProjectsFilterProjectsProject) GetLabels() []string { return v.Labels }

// GetAssignedTo returns GetAllProjectsFilterProjectsProject.AssignedTo, and is useful for accessing the field via an interface.
func (v *GetAllProjectsFilterProjectsProject) GetAssignedTo() string { return v.AssignedTo }

// GetDueDate returns GetAllProjectsFilterProjectsProject.DueDate, and is useful for accessing the field via an interface.
func (v *GetAllProjectsFilterProjectsProject) GetDueDate() string { return v.DueDate }

// GetStatus returns GetAllProjectsFilterProjectsProject.Status, and is useful for accessing the field via an interface.
func (v *GetAllProjectsFilterProjectsProject) GetStatus() string { return v.Status }

// GetCreatedAt returns GetAllProjectsFilterProjectsProject.CreatedAt, and is useful for accessing the field via an interface.
func (v *GetAllProjectsFilterProjectsProject) GetCreatedAt() string { return v.CreatedAt }

// GetUpdatedAt returns GetAllProjectsFilterProjectsProject.UpdatedAt, and is useful for accessing the field via an interface.
func (v *GetAllProjectsFilterProjectsProject) GetUpdatedAt() string { return v.UpdatedAt }

// GetTasks returns GetAllProjectsFilterProjectsProject.Tasks, and is useful for accessing the field via an interface.
func (v *GetAllProjectsFilterProjectsProject) GetTasks() []GetAllProjectsFilterProjectsProjectTasksTask {
	return v.Tasks
}

// GetAllProjectsFilterProjectsProjectTasksTask includes the requested fields of the GraphQL type Task.
type GetAllProjectsFilterProjectsProjectTasksTask struct {
	Id string `json:"id"`
}

// GetId returns GetAllProjectsFilterProjectsProjectTasksTask.Id, and is useful for accessing the field via an interface.
func (v *GetAllProjectsFilterProjectsProjectTasksTask) GetId() string { return v.Id }

// GetAllProjectsResponse is returned by GetAllProjects on success.
type GetAllProjectsResponse struct {
	// Get projects filtered by SOP standard operating proceedure
	FilterProjects []GetAllProjectsFilterProjectsProject `json:"filterProjects"`
}

// GetFilterProjects returns GetAllProjectsResponse.FilterProjects, and is useful for accessing the field via an interface.
func (v *GetAllProjectsResponse) GetFilterProjects() []GetAllProjectsFilterProjectsProject {
	return v.FilterProjects
}

// GetAllStrategiesGetAllStrategiesStrategy includes the requested fields of the GraphQL type Strategy.
type GetAllStrategiesGetAllStrategiesStrategy struct {
	BotInstanceName      string  `json:"BotInstanceName"`
	TradeDuration        int     `json:"TradeDuration"`
	IncrementsATR        int     `json:"IncrementsATR"`
	LongSMADuration      int     `json:"LongSMADuration"`
	ShortSMADuration     int     `json:"ShortSMADuration"`
	WINCounter           int     `json:"WINCounter"`
	LOSSCounter          int     `json:"LOSSCounter"`
	TIMEOUTGainCounter   int     `json:"TIMEOUTGainCounter"`
	TIMEOUTLossCounter   int     `json:"TIMEOUTLossCounter"`
	NetGainCounter       int     `json:"NetGainCounter"`
	NetLossCounter       int     `json:"NetLossCounter"`
	AccountBalance       float64 `json:"AccountBalance"`
	MovingAveMomentum    float64 `json:"MovingAveMomentum"`
	TakeProfitPercentage float64 `json:"TakeProfitPercentage"`
	StopLossPercentage   float64 `json:"StopLossPercentage"`
	ATRtollerance        float64 `json:"ATRtollerance"`
	FeesTotal            float64 `json:"FeesTotal"`
	Tested               bool    `json:"Tested"`
	Owner                string  `json:"Owner"`
	CreatedOn            int     `json:"CreatedOn"`
}

// GetBotInstanceName returns GetAllStrategiesGetAllStrategiesStrategy.BotInstanceName, and is useful for accessing the field via an interface.
func (v *GetAllStrategiesGetAllStrategiesStrategy) GetBotInstanceName() string {
	return v.BotInstanceName
}

// GetTradeDuration returns GetAllStrategiesGetAllStrategiesStrategy.TradeDuration, and is useful for accessing the field via an interface.
func (v *GetAllStrategiesGetAllStrategiesStrategy) GetTradeDuration() int { return v.TradeDuration }

// GetIncrementsATR returns GetAllStrategiesGetAllStrategiesStrategy.IncrementsATR, and is useful for accessing the field via an interface.
func (v *GetAllStrategiesGetAllStrategiesStrategy) GetIncrementsATR() int { return v.IncrementsATR }

// GetLongSMADuration returns GetAllStrategiesGetAllStrategiesStrategy.LongSMADuration, and is useful for accessing the field via an interface.
func (v *GetAllStrategiesGetAllStrategiesStrategy) GetLongSMADuration() int { return v.LongSMADuration }

// GetShortSMADuration returns GetAllStrategiesGetAllStrategiesStrategy.ShortSMADuration, and is useful for accessing the field via an interface.
func (v *GetAllStrategiesGetAllStrategiesStrategy) GetShortSMADuration() int {
	return v.ShortSMADuration
}

// GetWINCounter returns GetAllStrategiesGetAllStrategiesStrategy.WINCounter, and is useful for accessing the field via an interface.
func (v *GetAllStrategiesGetAllStrategiesStrategy) GetWINCounter() int { return v.WINCounter }

// GetLOSSCounter returns GetAllStrategiesGetAllStrategiesStrategy.LOSSCounter, and is useful for accessing the field via an interface.
func (v *GetAllStrategiesGetAllStrategiesStrategy) GetLOSSCounter() int { return v.LOSSCounter }

// GetTIMEOUTGainCounter returns GetAllStrategiesGetAllStrategiesStrategy.TIMEOUTGainCounter, and is useful for accessing the field via an interface.
func (v *GetAllStrategiesGetAllStrategiesStrategy) GetTIMEOUTGainCounter() int {
	return v.TIMEOUTGainCounter
}

// GetTIMEOUTLossCounter returns GetAllStrategiesGetAllStrategiesStrategy.TIMEOUTLossCounter, and is useful for accessing the field via an interface.
func (v *GetAllStrategiesGetAllStrategiesStrategy) GetTIMEOUTLossCounter() int {
	return v.TIMEOUTLossCounter
}

// GetNetGainCounter returns GetAllStrategiesGetAllStrategiesStrategy.NetGainCounter, and is useful for accessing the field via an interface.
func (v *GetAllStrategiesGetAllStrategiesStrategy) GetNetGainCounter() int { return v.NetGainCounter }

// GetNetLossCounter returns GetAllStrategiesGetAllStrategiesStrategy.NetLossCounter, and is useful for accessing the field via an interface.
func (v *GetAllStrategiesGetAllStrategiesStrategy) GetNetLossCounter() int { return v.NetLossCounter }

// GetAccountBalance returns GetAllStrategiesGetAllStrategiesStrategy.AccountBalance, and is useful for accessing the field via an interface.
func (v *GetAllStrategiesGetAllStrategiesStrategy) GetAccountBalance() float64 {
	return v.AccountBalance
}

// GetMovingAveMomentum returns GetAllStrategiesGetAllStrategiesStrategy.MovingAveMomentum, and is useful for accessing the field via an interface.
func (v *GetAllStrategiesGetAllStrategiesStrategy) GetMovingAveMomentum() float64 {
	return v.MovingAveMomentum
}

// GetTakeProfitPercentage returns GetAllStrategiesGetAllStrategiesStrategy.TakeProfitPercentage, and is useful for accessing the field via an interface.
func (v *GetAllStrategiesGetAllStrategiesStrategy) GetTakeProfitPercentage() float64 {
	return v.TakeProfitPercentage
}

// GetStopLossPercentage returns GetAllStrategiesGetAllStrategiesStrategy.StopLossPercentage, and is useful for accessing the field via an interface.
func (v *GetAllStrategiesGetAllStrategiesStrategy) GetStopLossPercentage() float64 {
	return v.StopLossPercentage
}

// GetATRtollerance returns GetAllStrategiesGetAllStrategiesStrategy.ATRtollerance, and is useful for accessing the field via an interface.
func (v *GetAllStrategiesGetAllStrategiesStrategy) GetATRtollerance() float64 { return v.ATRtollerance }

// GetFeesTotal returns GetAllStrategiesGetAllStrategiesStrategy.FeesTotal, and is useful for accessing the field via an interface.
func (v *GetAllStrategiesGetAllStrategiesStrategy) GetFeesTotal() float64 { return v.FeesTotal }

// GetTested returns GetAllStrategiesGetAllStrategiesStrategy.Tested, and is useful for accessing the field via an interface.
func (v *GetAllStrategiesGetAllStrategiesStrategy) GetTested() bool { return v.Tested }

// GetOwner returns GetAllStrategiesGetAllStrategiesStrategy.Owner, and is useful for accessing the field via an interface.
func (v *GetAllStrategiesGetAllStrategiesStrategy) GetOwner() string { return v.Owner }

// GetCreatedOn returns GetAllStrategiesGetAllStrategiesStrategy.CreatedOn, and is useful for accessing the field via an interface.
func (v *GetAllStrategiesGetAllStrategiesStrategy) GetCreatedOn() int { return v.CreatedOn }

// GetAllStrategiesResponse is returned by GetAllStrategies on success.
type GetAllStrategiesResponse struct {
	// Get all strategies
	GetAllStrategies []GetAllStrategiesGetAllStrategiesStrategy `json:"getAllStrategies"`
}

// GetGetAllStrategies returns GetAllStrategiesResponse.GetAllStrategies, and is useful for accessing the field via an interface.
func (v *GetAllStrategiesResponse) GetGetAllStrategies() []GetAllStrategiesGetAllStrategiesStrategy {
	return v.GetAllStrategies
}

// GetAllTasksAllTasksTask includes the requested fields of the GraphQL type Task.
type GetAllTasksAllTasksTask struct {
	Id          string   `json:"id"`
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Status      string   `json:"status"`
	Labels      []string `json:"labels"`
	AssignedTo  string   `json:"assignedTo"`
	DueDate     string   `json:"dueDate"`
	DeferDate   string   `json:"deferDate"`
	Department  string   `json:"department"`
	ProjectId   string   `json:"projectId"`
	Duration    int      `json:"duration"`
	CreatedAt   string   `json:"createdAt"`
	UpdatedAt   string   `json:"updatedAt"`
}

// GetId returns GetAllTasksAllTasksTask.Id, and is useful for accessing the field via an interface.
func (v *GetAllTasksAllTasksTask) GetId() string { return v.Id }

// GetTitle returns GetAllTasksAllTasksTask.Title, and is useful for accessing the field via an interface.
func (v *GetAllTasksAllTasksTask) GetTitle() string { return v.Title }

// GetDescription returns GetAllTasksAllTasksTask.Description, and is useful for accessing the field via an interface.
func (v *GetAllTasksAllTasksTask) GetDescription() string { return v.Description }

// GetStatus returns GetAllTasksAllTasksTask.Status, and is useful for accessing the field via an interface.
func (v *GetAllTasksAllTasksTask) GetStatus() string { return v.Status }

// GetLabels returns GetAllTasksAllTasksTask.Labels, and is useful for accessing the field via an interface.
func (v *GetAllTasksAllTasksTask) GetLabels() []string { return v.Labels }

// GetAssignedTo returns GetAllTasksAllTasksTask.AssignedTo, and is useful for accessing the field via an interface.
func (v *GetAllTasksAllTasksTask) GetAssignedTo() string { return v.AssignedTo }

// GetDueDate returns GetAllTasksAllTasksTask.DueDate, and is useful for accessing the field via an interface.
func (v *GetAllTasksAllTasksTask) GetDueDate() string { return v.DueDate }

// GetDeferDate returns GetAllTasksAllTasksTask.DeferDate, and is useful for accessing the field via an interface.
func (v *GetAllTasksAllTasksTask) GetDeferDate() string { return v.DeferDate }

// GetDepartment returns GetAllTasksAllTasksTask.Department, and is useful for accessing the field via an interface.
func (v *GetAllTasksAllTasksTask) GetDepartment() string { return v.Department }

// GetProjectId returns GetAllTasksAllTasksTask.ProjectId, and is useful for accessing the field via an interface.
func (v *GetAllTasksAllTasksTask) GetProjectId() string { return v.ProjectId }

// GetDuration returns GetAllTasksAllTasksTask.Duration, and is useful for accessing the field via an interface.
func (v *GetAllTasksAllTasksTask) GetDuration() int { return v.Duration }

// GetCreatedAt returns GetAllTasksAllTasksTask.CreatedAt, and is useful for accessing the field via an interface.
func (v *GetAllTasksAllTasksTask) GetCreatedAt() string { return v.CreatedAt }

// GetUpdatedAt returns GetAllTasksAllTasksTask.UpdatedAt, and is useful for accessing the field via an interface.
func (v *GetAllTasksAllTasksTask) GetUpdatedAt() string { return v.UpdatedAt }

// GetAllTasksResponse is returned by GetAllTasks on success.
type GetAllTasksResponse struct {
	// Get all tasks
	AllTasks []GetAllTasksAllTasksTask `json:"allTasks"`
}

// GetAllTasks returns GetAllTasksResponse.AllTasks, and is useful for accessing the field via an interface.
func (v *GetAllTasksResponse) GetAllTasks() []GetAllTasksAllTasksTask { return v.AllTasks }

// GetHistoricPricesAtTimestampGetHistoricPricesAtTimestampHistoricPrices includes the requested fields of the GraphQL type HistoricPrices.
type GetHistoricPricesAtTimestampGetHistoricPricesAtTimestampHistoricPrices struct {
	Pair      []GetHistoricPricesAtTimestampGetHistoricPricesAtTimestampHistoricPricesPair `json:"Pair"`
	Timestamp int                                                                          `json:"Timestamp"`
}

// GetPair returns GetHistoricPricesAtTimestampGetHistoricPricesAtTimestampHistoricPrices.Pair, and is useful for accessing the field via an interface.
func (v *GetHistoricPricesAtTimestampGetHistoricPricesAtTimestampHistoricPrices) GetPair() []GetHistoricPricesAtTimestampGetHistoricPricesAtTimestampHistoricPricesPair {
	return v.Pair
}

// GetTimestamp returns GetHistoricPricesAtTimestampGetHistoricPricesAtTimestampHistoricPrices.Timestamp, and is useful for accessing the field via an interface.
func (v *GetHistoricPricesAtTimestampGetHistoricPricesAtTimestampHistoricPrices) GetTimestamp() int {
	return v.Timestamp
}

// GetHistoricPricesAtTimestampGetHistoricPricesAtTimestampHistoricPricesPair includes the requested fields of the GraphQL type Pair.
type GetHistoricPricesAtTimestampGetHistoricPricesAtTimestampHistoricPricesPair struct {
	Symbol string `json:"Symbol"`
	Price  string `json:"Price"`
}

// GetSymbol returns GetHistoricPricesAtTimestampGetHistoricPricesAtTimestampHistoricPricesPair.Symbol, and is useful for accessing the field via an interface.
func (v *GetHistoricPricesAtTimestampGetHistoricPricesAtTimestampHistoricPricesPair) GetSymbol() string {
	return v.Symbol
}

// GetPrice returns GetHistoricPricesAtTimestampGetHistoricPricesAtTimestampHistoricPricesPair.Price, and is useful for accessing the field via an interface.
func (v *GetHistoricPricesAtTimestampGetHistoricPricesAtTimestampHistoricPricesPair) GetPrice() string {
	return v.Price
}

// GetHistoricPricesAtTimestampResponse is returned by GetHistoricPricesAtTimestamp on success.
type GetHistoricPricesAtTimestampResponse struct {
	// Gets all prices data at a given timestamp
	GetHistoricPricesAtTimestamp []GetHistoricPricesAtTimestampGetHistoricPricesAtTimestampHistoricPrices `json:"getHistoricPricesAtTimestamp"`
}

// GetGetHistoricPricesAtTimestamp returns GetHistoricPricesAtTimestampResponse.GetHistoricPricesAtTimestamp, and is useful for accessing the field via an interface.
func (v *GetHistoricPricesAtTimestampResponse) GetGetHistoricPricesAtTimestamp() []GetHistoricPricesAtTimestampGetHistoricPricesAtTimestampHistoricPrices {
	return v.GetHistoricPricesAtTimestamp
}

// GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStats includes the requested fields of the GraphQL type HistoricTickerStats.
type GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStats struct {
	Timestamp int                                                                                                     `json:"Timestamp"`
	Stats     []GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats `json:"Stats"`
}

// GetTimestamp returns GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStats.Timestamp, and is useful for accessing the field via an interface.
func (v *GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStats) GetTimestamp() int {
	return v.Timestamp
}

// GetStats returns GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStats.Stats, and is useful for accessing the field via an interface.
func (v *GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStats) GetStats() []GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats {
	return v.Stats
}

// GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats includes the requested fields of the GraphQL type TickerStats.
type GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats struct {
	Symbol            string `json:"Symbol"`
	PriceChange       string `json:"PriceChange"`
	PriceChangePct    string `json:"PriceChangePct"`
	QuoteVolume       string `json:"QuoteVolume"`
	Volume            string `json:"Volume"`
	TradeCount        int    `json:"TradeCount"`
	HighPrice         string `json:"HighPrice"`
	LowPrice          string `json:"LowPrice"`
	LastPrice         string `json:"LastPrice"`
	LiquidityEstimate string `json:"LiquidityEstimate"`
}

// GetSymbol returns GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats.Symbol, and is useful for accessing the field via an interface.
func (v *GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats) GetSymbol() string {
	return v.Symbol
}

// GetPriceChange returns GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats.PriceChange, and is useful for accessing the field via an interface.
func (v *GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats) GetPriceChange() string {
	return v.PriceChange
}

// GetPriceChangePct returns GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats.PriceChangePct, and is useful for accessing the field via an interface.
func (v *GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats) GetPriceChangePct() string {
	return v.PriceChangePct
}

// GetQuoteVolume returns GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats.QuoteVolume, and is useful for accessing the field via an interface.
func (v *GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats) GetQuoteVolume() string {
	return v.QuoteVolume
}

// GetVolume returns GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats.Volume, and is useful for accessing the field via an interface.
func (v *GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats) GetVolume() string {
	return v.Volume
}

// GetTradeCount returns GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats.TradeCount, and is useful for accessing the field via an interface.
func (v *GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats) GetTradeCount() int {
	return v.TradeCount
}

// GetHighPrice returns GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats.HighPrice, and is useful for accessing the field via an interface.
func (v *GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats) GetHighPrice() string {
	return v.HighPrice
}

// GetLowPrice returns GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats.LowPrice, and is useful for accessing the field via an interface.
func (v *GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats) GetLowPrice() string {
	return v.LowPrice
}

// GetLastPrice returns GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats.LastPrice, and is useful for accessing the field via an interface.
func (v *GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats) GetLastPrice() string {
	return v.LastPrice
}

// GetLiquidityEstimate returns GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats.LiquidityEstimate, and is useful for accessing the field via an interface.
func (v *GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStatsStatsTickerStats) GetLiquidityEstimate() string {
	return v.LiquidityEstimate
}

// GetHistoricTickerStatsAtTimestampResponse is returned by GetHistoricTickerStatsAtTimestamp on success.
type GetHistoricTickerStatsAtTimestampResponse struct {
	// Gets all 24h Ticker Stats at a specific timestamp
	GetHistoricTickerStatsAtTimestamp []GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStats `json:"getHistoricTickerStatsAtTimestamp"`
}

// GetGetHistoricTickerStatsAtTimestamp returns GetHistoricTickerStatsAtTimestampResponse.GetHistoricTickerStatsAtTimestamp, and is useful for accessing the field via an interface.
func (v *GetHistoricTickerStatsAtTimestampResponse) GetGetHistoricTickerStatsAtTimestamp() []GetHistoricTickerStatsAtTimestampGetHistoricTickerStatsAtTimestampHistoricTickerStats {
	return v.GetHistoricTickerStatsAtTimestamp
}

// GetPriceDataGetHistoricPriceHistoricPrices includes the requested fields of the GraphQL type HistoricPrices.
type GetPriceDataGetHistoricPriceHistoricPrices struct {
	Pair      []GetPriceDataGetHistoricPriceHistoricPricesPair `json:"Pair"`
	Timestamp int                                              `json:"Timestamp"`
}

// GetPair returns GetPriceDataGetHistoricPriceHistoricPrices.Pair, and is useful for accessing the field via an interface.
func (v *GetPriceDataGetHistoricPriceHistoricPrices) GetPair() []GetPriceDataGetHistoricPriceHistoricPricesPair {
	return v.Pair
}

// GetTimestamp returns GetPriceDataGetHistoricPriceHistoricPrices.Timestamp, and is useful for accessing the field via an interface.
func (v *GetPriceDataGetHistoricPriceHistoricPrices) GetTimestamp() int { return v.Timestamp }

// GetPriceDataGetHistoricPriceHistoricPricesPair includes the requested fields of the GraphQL type Pair.
type GetPriceDataGetHistoricPriceHistoricPricesPair struct {
	Symbol string `json:"Symbol"`
	Price  string `json:"Price"`
}

// GetSymbol returns GetPriceDataGetHistoricPriceHistoricPricesPair.Symbol, and is useful for accessing the field via an interface.
func (v *GetPriceDataGetHistoricPriceHistoricPricesPair) GetSymbol() string { return v.Symbol }

// GetPrice returns GetPriceDataGetHistoricPriceHistoricPricesPair.Price, and is useful for accessing the field via an interface.
func (v *GetPriceDataGetHistoricPriceHistoricPricesPair) GetPrice() string { return v.Price }

// GetPriceDataResponse is returned by GetPriceData on success.
type GetPriceDataResponse struct {
	// Fetches price data for a given symbol up to a given limit of records
	GetHistoricPrice []GetPriceDataGetHistoricPriceHistoricPrices `json:"getHistoricPrice"`
}

// GetGetHistoricPrice returns GetPriceDataResponse.GetHistoricPrice, and is useful for accessing the field via an interface.
func (v *GetPriceDataResponse) GetGetHistoricPrice() []GetPriceDataGetHistoricPriceHistoricPrices {
	return v.GetHistoricPrice
}

// GetUserByEmailGetUserByEmailUser includes the requested fields of the GraphQL type User.
type GetUserByEmailGetUserByEmailUser struct {
	Id    string `json:"id"`
	Email string `json:"email"`
}

// GetId returns GetUserByEmailGetUserByEmailUser.Id, and is useful for accessing the field via an interface.
func (v *GetUserByEmailGetUserByEmailUser) GetId() string { return v.Id }

// GetEmail returns GetUserByEmailGetUserByEmailUser.Email, and is useful for accessing the field via an interface.
func (v *GetUserByEmailGetUserByEmailUser) GetEmail() string { return v.Email }

// GetUserByEmailResponse is returned by GetUserByEmail on success.
type GetUserByEmailResponse struct {
	GetUserByEmail GetUserByEmailGetUserByEmailUser `json:"getUserByEmail"`
}

// GetGetUserByEmail returns GetUserByEmailResponse.GetUserByEmail, and is useful for accessing the field via an interface.
func (v *GetUserByEmailResponse) GetGetUserByEmail() GetUserByEmailGetUserByEmailUser {
	return v.GetUserByEmail
}

type NewHistoricPriceInput struct {
	Pairs     []PairInput `json:"Pairs"`
	Timestamp int         `json:"Timestamp"`
}

// GetPairs returns NewHistoricPriceInput.Pairs, and is useful for accessing the field via an interface.
func (v *NewHistoricPriceInput) GetPairs() []PairInput { return v.Pairs }

// GetTimestamp returns NewHistoricPriceInput.Timestamp, and is useful for accessing the field via an interface.
func (v *NewHistoricPriceInput) GetTimestamp() int { return v.Timestamp }

type NewHistoricTickerStatsInput struct {
	Timestamp int                `json:"Timestamp"`
	Stats     []TickerStatsInput `json:"Stats"`
}

// GetTimestamp returns NewHistoricTickerStatsInput.Timestamp, and is useful for accessing the field via an interface.
func (v *NewHistoricTickerStatsInput) GetTimestamp() int { return v.Timestamp }

// GetStats returns NewHistoricTickerStatsInput.Stats, and is useful for accessing the field via an interface.
func (v *NewHistoricTickerStatsInput) GetStats() []TickerStatsInput { return v.Stats }

type PairInput struct {
	Symbol string `json:"Symbol"`
	Price  string `json:"Price"`
}

// GetSymbol returns PairInput.Symbol, and is useful for accessing the field via an interface.
func (v *PairInput) GetSymbol() string { return v.Symbol }

// GetPrice returns PairInput.Price, and is useful for accessing the field via an interface.
func (v *PairInput) GetPrice() string { return v.Price }

type TickerStatsInput struct {
	Symbol            string `json:"Symbol"`
	PriceChange       string `json:"PriceChange"`
	PriceChangePct    string `json:"PriceChangePct"`
	QuoteVolume       string `json:"QuoteVolume"`
	Volume            string `json:"Volume"`
	TradeCount        int    `json:"TradeCount"`
	HighPrice         string `json:"HighPrice"`
	LowPrice          string `json:"LowPrice"`
	LastPrice         string `json:"LastPrice"`
	LiquidityEstimate string `json:"LiquidityEstimate"`
}

// GetSymbol returns TickerStatsInput.Symbol, and is useful for accessing the field via an interface.
func (v *TickerStatsInput) GetSymbol() string { return v.Symbol }

// GetPriceChange returns TickerStatsInput.PriceChange, and is useful for accessing the field via an interface.
func (v *TickerStatsInput) GetPriceChange() string { return v.PriceChange }

// GetPriceChangePct returns TickerStatsInput.PriceChangePct, and is useful for accessing the field via an interface.
func (v *TickerStatsInput) GetPriceChangePct() string { return v.PriceChangePct }

// GetQuoteVolume returns TickerStatsInput.QuoteVolume, and is useful for accessing the field via an interface.
func (v *TickerStatsInput) GetQuoteVolume() string { return v.QuoteVolume }

// GetVolume returns TickerStatsInput.Volume, and is useful for accessing the field via an interface.
func (v *TickerStatsInput) GetVolume() string { return v.Volume }

// GetTradeCount returns TickerStatsInput.TradeCount, and is useful for accessing the field via an interface.
func (v *TickerStatsInput) GetTradeCount() int { return v.TradeCount }

// GetHighPrice returns TickerStatsInput.HighPrice, and is useful for accessing the field via an interface.
func (v *TickerStatsInput) GetHighPrice() string { return v.HighPrice }

// GetLowPrice returns TickerStatsInput.LowPrice, and is useful for accessing the field via an interface.
func (v *TickerStatsInput) GetLowPrice() string { return v.LowPrice }

// GetLastPrice returns TickerStatsInput.LastPrice, and is useful for accessing the field via an interface.
func (v *TickerStatsInput) GetLastPrice() string { return v.LastPrice }

// GetLiquidityEstimate returns TickerStatsInput.LiquidityEstimate, and is useful for accessing the field via an interface.
func (v *TickerStatsInput) GetLiquidityEstimate() string { return v.LiquidityEstimate }

// __CreateActivityReportInput is used internally by genqlient
type __CreateActivityReportInput struct {
	TimeStamp      int     `json:"timeStamp"`
	Qty            int     `json:"qty"`
	AvgGain        float64 `json:"avgGain"`
	TopAGain       float64 `json:"topAGain"`
	TopBGain       float64 `json:"topBGain"`
	TopCGain       float64 `json:"topCGain"`
	FearGreedIndex int     `json:"fearGreedIndex"`
}

// GetTimeStamp returns __CreateActivityReportInput.TimeStamp, and is useful for accessing the field via an interface.
func (v *__CreateActivityReportInput) GetTimeStamp() int { return v.TimeStamp }

// GetQty returns __CreateActivityReportInput.Qty, and is useful for accessing the field via an interface.
func (v *__CreateActivityReportInput) GetQty() int { return v.Qty }

// GetAvgGain returns __CreateActivityReportInput.AvgGain, and is useful for accessing the field via an interface.
func (v *__CreateActivityReportInput) GetAvgGain() float64 { return v.AvgGain }

// GetTopAGain returns __CreateActivityReportInput.TopAGain, and is useful for accessing the field via an interface.
func (v *__CreateActivityReportInput) GetTopAGain() float64 { return v.TopAGain }

// GetTopBGain returns __CreateActivityReportInput.TopBGain, and is useful for accessing the field via an interface.
func (v *__CreateActivityReportInput) GetTopBGain() float64 { return v.TopBGain }

// GetTopCGain returns __CreateActivityReportInput.TopCGain, and is useful for accessing the field via an interface.
func (v *__CreateActivityReportInput) GetTopCGain() float64 { return v.TopCGain }

// GetFearGreedIndex returns __CreateActivityReportInput.FearGreedIndex, and is useful for accessing the field via an interface.
func (v *__CreateActivityReportInput) GetFearGreedIndex() int { return v.FearGreedIndex }

// __CreateHistoricPricesInput is used internally by genqlient
type __CreateHistoricPricesInput struct {
	Input NewHistoricPriceInput `json:"input"`
}

// GetInput returns __CreateHistoricPricesInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateHistoricPricesInput) GetInput() NewHistoricPriceInput { return v.Input }

// __CreateHistoricTickerStatsInput is used internally by genqlient
type __CreateHistoricTickerStatsInput struct {
	Input NewHistoricTickerStatsInput `json:"input"`
}

// GetInput returns __CreateHistoricTickerStatsInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateHistoricTickerStatsInput) GetInput() NewHistoricTickerStatsInput { return v.Input }

// __CreateProjectInput is used internally by genqlient
type __CreateProjectInput struct {
	Input CreateProjectInput `json:"input"`
}

// GetInput returns __CreateProjectInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateProjectInput) GetInput() CreateProjectInput { return v.Input }

// __CreateTaskInput is used internally by genqlient
type __CreateTaskInput struct {
	Input CreateTaskInput `json:"input"`
}

// GetInput returns __CreateTaskInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateTaskInput) GetInput() CreateTaskInput { return v.Input }

// __CreateTradeOutcomeReportInput is used internally by genqlient
type __CreateTradeOutcomeReportInput struct {
	TimeStamp        int     `json:"timeStamp"`
	BotName          string  `json:"botName"`
	PercentageChange float64 `json:"percentageChange"`
	Balance          float64 `json:"balance"`
	Symbol           string  `json:"symbol"`
	Outcome          string  `json:"outcome"`
	Fee              float64 `json:"Fee"`
	ElapsedTime      int     `json:"elapsedTime"`
	Volume           float64 `json:"volume"`
	FearGreedIndex   int     `json:"fearGreedIndex"`
	MarketStatus     string  `json:"marketStatus"`
}

// GetTimeStamp returns __CreateTradeOutcomeReportInput.TimeStamp, and is useful for accessing the field via an interface.
func (v *__CreateTradeOutcomeReportInput) GetTimeStamp() int { return v.TimeStamp }

// GetBotName returns __CreateTradeOutcomeReportInput.BotName, and is useful for accessing the field via an interface.
func (v *__CreateTradeOutcomeReportInput) GetBotName() string { return v.BotName }

// GetPercentageChange returns __CreateTradeOutcomeReportInput.PercentageChange, and is useful for accessing the field via an interface.
func (v *__CreateTradeOutcomeReportInput) GetPercentageChange() float64 { return v.PercentageChange }

// GetBalance returns __CreateTradeOutcomeReportInput.Balance, and is useful for accessing the field via an interface.
func (v *__CreateTradeOutcomeReportInput) GetBalance() float64 { return v.Balance }

// GetSymbol returns __CreateTradeOutcomeReportInput.Symbol, and is useful for accessing the field via an interface.
func (v *__CreateTradeOutcomeReportInput) GetSymbol() string { return v.Symbol }

// GetOutcome returns __CreateTradeOutcomeReportInput.Outcome, and is useful for accessing the field via an interface.
func (v *__CreateTradeOutcomeReportInput) GetOutcome() string { return v.Outcome }

// GetFee returns __CreateTradeOutcomeReportInput.Fee, and is useful for accessing the field via an interface.
func (v *__CreateTradeOutcomeReportInput) GetFee() float64 { return v.Fee }

// GetElapsedTime returns __CreateTradeOutcomeReportInput.ElapsedTime, and is useful for accessing the field via an interface.
func (v *__CreateTradeOutcomeReportInput) GetElapsedTime() int { return v.ElapsedTime }

// GetVolume returns __CreateTradeOutcomeReportInput.Volume, and is useful for accessing the field via an interface.
func (v *__CreateTradeOutcomeReportInput) GetVolume() float64 { return v.Volume }

// GetFearGreedIndex returns __CreateTradeOutcomeReportInput.FearGreedIndex, and is useful for accessing the field via an interface.
func (v *__CreateTradeOutcomeReportInput) GetFearGreedIndex() int { return v.FearGreedIndex }

// GetMarketStatus returns __CreateTradeOutcomeReportInput.MarketStatus, and is useful for accessing the field via an interface.
func (v *__CreateTradeOutcomeReportInput) GetMarketStatus() string { return v.MarketStatus }

// __CreateUserInput is used internally by genqlient
type __CreateUserInput struct {
	Input CreateUserInput `json:"input"`
}

// GetInput returns __CreateUserInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateUserInput) GetInput() CreateUserInput { return v.Input }

// __GetAllProjectsInput is used internally by genqlient
type __GetAllProjectsInput struct {
	IsSop bool `json:"isSop"`
}

// GetIsSop returns __GetAllProjectsInput.IsSop, and is useful for accessing the field via an interface.
func (v *__GetAllProjectsInput) GetIsSop() bool { return v.IsSop }

// __GetHistoricPricesAtTimestampInput is used internally by genqlient
type __GetHistoricPricesAtTimestampInput struct {
	Datetime int `json:"datetime"`
}

// GetDatetime returns __GetHistoricPricesAtTimestampInput.Datetime, and is useful for accessing the field via an interface.
func (v *__GetHistoricPricesAtTimestampInput) GetDatetime() int { return v.Datetime }

// __GetHistoricTickerStatsAtTimestampInput is used internally by genqlient
type __GetHistoricTickerStatsAtTimestampInput struct {
	Datetime int `json:"datetime"`
}

// GetDatetime returns __GetHistoricTickerStatsAtTimestampInput.Datetime, and is useful for accessing the field via an interface.
func (v *__GetHistoricTickerStatsAtTimestampInput) GetDatetime() int { return v.Datetime }

// __GetPriceDataInput is used internally by genqlient
type __GetPriceDataInput struct {
	Symbol string `json:"symbol"`
	Limit  int    `json:"limit"`
}

// GetSymbol returns __GetPriceDataInput.Symbol, and is useful for accessing the field via an interface.
func (v *__GetPriceDataInput) GetSymbol() string { return v.Symbol }

// GetLimit returns __GetPriceDataInput.Limit, and is useful for accessing the field via an interface.
func (v *__GetPriceDataInput) GetLimit() int { return v.Limit }

// __GetUserByEmailInput is used internally by genqlient
type __GetUserByEmailInput struct {
	Email string `json:"email"`
}

// GetEmail returns __GetUserByEmailInput.Email, and is useful for accessing the field via an interface.
func (v *__GetUserByEmailInput) GetEmail() string { return v.Email }

// The mutation executed by CreateActivityReport.
const CreateActivityReport_Operation = `
mutation CreateActivityReport ($timeStamp: Int!, $qty: Int!, $avgGain: Float!, $topAGain: Float, $topBGain: Float, $topCGain: Float, $fearGreedIndex: Int!) {
	createActivityReport(input: {Timestamp:$timeStamp,Qty:$qty,AvgGain:$avgGain,TopAGain:$topAGain,TopBGain:$topBGain,TopCGain:$topCGain,FearGreedIndex:$fearGreedIndex}) {
		_id
		Timestamp
		Qty
		AvgGain
		TopAGain
		TopBGain
		TopCGain
		FearGreedIndex
	}
}
`

func CreateActivityReport(
	ctx_ context.Context,
	client_ graphql.Client,
	timeStamp int,
	qty int,
	avgGain float64,
	topAGain float64,
	topBGain float64,
	topCGain float64,
	fearGreedIndex int,
) (data_ *CreateActivityReportResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateActivityReport",
		Query:  CreateActivityReport_Operation,
		Variables: &__CreateActivityReportInput{
			TimeStamp:      timeStamp,
			Qty:            qty,
			AvgGain:        avgGain,
			TopAGain:       topAGain,
			TopBGain:       topBGain,
			TopCGain:       topCGain,
			FearGreedIndex: fearGreedIndex,
		},
	}

	data_ = &CreateActivityReportResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by CreateHistoricPrices.
const CreateHistoricPrices_Operation = `
mutation CreateHistoricPrices ($input: NewHistoricPriceInput!) {
	createHistoricPrices(input: $input) {
		Pair {
			Symbol
			Price
		}
	}
}
`

func CreateHistoricPrices(
	ctx_ context.Context,
	client_ graphql.Client,
	input NewHistoricPriceInput,
) (data_ *CreateHistoricPricesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateHistoricPrices",
		Query:  CreateHistoricPrices_Operation,
		Variables: &__CreateHistoricPricesInput{
			Input: input,
		},
	}

	data_ = &CreateHistoricPricesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by CreateHistoricTickerStats.
const CreateHistoricTickerStats_Operation = `
mutation CreateHistoricTickerStats ($input: NewHistoricTickerStatsInput!) {
	createHistoricTickerStats(input: $input) {
		Timestamp
		Stats {
			Symbol
			PriceChange
			PriceChangePct
			QuoteVolume
			Volume
			TradeCount
			HighPrice
			LowPrice
			LastPrice
			LiquidityEstimate
		}
		CreatedAt
	}
}
`

func CreateHistoricTickerStats(
	ctx_ context.Context,
	client_ graphql.Client,
	input NewHistoricTickerStatsInput,
) (data_ *CreateHistoricTickerStatsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateHistoricTickerStats",
		Query:  CreateHistoricTickerStats_Operation,
		Variables: &__CreateHistoricTickerStatsInput{
			Input: input,
		},
	}

	data_ = &CreateHistoricTickerStatsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by CreateProject.
const CreateProject_Operation = `
mutation CreateProject ($input: CreateProjectInput!) {
	createProject(input: $input) {
		id
		title
		sop
		description
		labels
		assignedTo
		dueDate
		status
		createdAt
		updatedAt
	}
}
`

func CreateProject(
	ctx_ context.Context,
	client_ graphql.Client,
	input CreateProjectInput,
) (data_ *CreateProjectResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateProject",
		Query:  CreateProject_Operation,
		Variables: &__CreateProjectInput{
			Input: input,
		},
	}

	data_ = &CreateProjectResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by CreateTask.
const CreateTask_Operation = `
mutation CreateTask ($input: CreateTaskInput!) {
	createTask(input: $input) {
		id
		title
		description
		status
		labels
		assignedTo
		dueDate
		deferDate
		department
		projectId
		duration
		createdAt
		updatedAt
	}
}
`

func CreateTask(
	ctx_ context.Context,
	client_ graphql.Client,
	input CreateTaskInput,
) (data_ *CreateTaskResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateTask",
		Query:  CreateTask_Operation,
		Variables: &__CreateTaskInput{
			Input: input,
		},
	}

	data_ = &CreateTaskResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by CreateTradeOutcomeReport.
const CreateTradeOutcomeReport_Operation = `
mutation CreateTradeOutcomeReport ($timeStamp: Int!, $botName: String!, $percentageChange: Float!, $balance: Float!, $symbol: String!, $outcome: String!, $Fee: Float, $elapsedTime: Int!, $volume: Float!, $fearGreedIndex: Int!, $marketStatus: String!) {
	createTradeOutcomeReport(input: {Timestamp:$timeStamp,BotName:$botName,PercentageChange:$percentageChange,Balance:$balance,Symbol:$symbol,Outcome:$outcome,Fee:$Fee,ElapsedTime:$elapsedTime,Volume:$volume,FearGreedIndex:$fearGreedIndex,MarketStatus:$marketStatus}) {
		_id
		Timestamp
		BotName
		PercentageChange
		Balance
		Symbol
		Outcome
		Fee
		ElapsedTime
		Volume
		FearGreedIndex
		MarketStatus
	}
}
`

func CreateTradeOutcomeReport(
	ctx_ context.Context,
	client_ graphql.Client,
	timeStamp int,
	botName string,
	percentageChange float64,
	balance float64,
	symbol string,
	outcome string,
	Fee float64,
	elapsedTime int,
	volume float64,
	fearGreedIndex int,
	marketStatus string,
) (data_ *CreateTradeOutcomeReportResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateTradeOutcomeReport",
		Query:  CreateTradeOutcomeReport_Operation,
		Variables: &__CreateTradeOutcomeReportInput{
			TimeStamp:        timeStamp,
			BotName:          botName,
			PercentageChange: percentageChange,
			Balance:          balance,
			Symbol:           symbol,
			Outcome:          outcome,
			Fee:              Fee,
			ElapsedTime:      elapsedTime,
			Volume:           volume,
			FearGreedIndex:   fearGreedIndex,
			MarketStatus:     marketStatus,
		},
	}

	data_ = &CreateTradeOutcomeReportResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by CreateUser.
const CreateUser_Operation = `
mutation CreateUser ($input: CreateUserInput!) {
	createUser(input: $input) {
		id
		firstName
		lastName
		email
		role
	}
}
`

func CreateUser(
	ctx_ context.Context,
	client_ graphql.Client,
	input CreateUserInput,
) (data_ *CreateUserResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateUser",
		Query:  CreateUser_Operation,
		Variables: &__CreateUserInput{
			Input: input,
		},
	}

	data_ = &CreateUserResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetAllProjects.
const GetAllProjects_Operation = `
query GetAllProjects ($isSop: Boolean) {
	filterProjects(filter: {sop:$isSop}) {
		id
		title
		sop
		description
		labels
		assignedTo
		dueDate
		status
		createdAt
		updatedAt
		tasks {
			id
		}
	}
}
`

func GetAllProjects(
	ctx_ context.Context,
	client_ graphql.Client,
	isSop bool,
) (data_ *GetAllProjectsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetAllProjects",
		Query:  GetAllProjects_Operation,
		Variables: &__GetAllProjectsInput{
			IsSop: isSop,
		},
	}

	data_ = &GetAllProjectsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetAllStrategies.
const GetAllStrategies_Operation = `
query GetAllStrategies {
	getAllStrategies {
		BotInstanceName
		TradeDuration
		IncrementsATR
		LongSMADuration
		ShortSMADuration
		WINCounter
		LOSSCounter
		TIMEOUTGainCounter
		TIMEOUTLossCounter
		NetGainCounter
		NetLossCounter
		AccountBalance
		MovingAveMomentum
		TakeProfitPercentage
		StopLossPercentage
		ATRtollerance
		FeesTotal
		Tested
		Owner
		CreatedOn
	}
}
`

func GetAllStrategies(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *GetAllStrategiesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetAllStrategies",
		Query:  GetAllStrategies_Operation,
	}

	data_ = &GetAllStrategiesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetAllTasks.
const GetAllTasks_Operation = `
query GetAllTasks {
	allTasks {
		id
		title
		description
		status
		labels
		assignedTo
		dueDate
		deferDate
		department
		projectId
		duration
		createdAt
		updatedAt
	}
}
`

func GetAllTasks(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *GetAllTasksResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetAllTasks",
		Query:  GetAllTasks_Operation,
	}

	data_ = &GetAllTasksResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetHistoricPricesAtTimestamp.
const GetHistoricPricesAtTimestamp_Operation = `
query GetHistoricPricesAtTimestamp ($datetime: Int!) {
	getHistoricPricesAtTimestamp(Timestamp: $datetime) {
		Pair {
			Symbol
			Price
		}
		Timestamp
	}
}
`

func GetHistoricPricesAtTimestamp(
	ctx_ context.Context,
	client_ graphql.Client,
	datetime int,
) (data_ *GetHistoricPricesAtTimestampResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetHistoricPricesAtTimestamp",
		Query:  GetHistoricPricesAtTimestamp_Operation,
		Variables: &__GetHistoricPricesAtTimestampInput{
			Datetime: datetime,
		},
	}

	data_ = &GetHistoricPricesAtTimestampResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetHistoricTickerStatsAtTimestamp.
const GetHistoricTickerStatsAtTimestamp_Operation = `
query GetHistoricTickerStatsAtTimestamp ($datetime: Int!) {
	getHistoricTickerStatsAtTimestamp(Timestamp: $datetime) {
		Timestamp
		Stats {
			Symbol
			PriceChange
			PriceChangePct
			QuoteVolume
			Volume
			TradeCount
			HighPrice
			LowPrice
			LastPrice
			LiquidityEstimate
		}
	}
}
`

func GetHistoricTickerStatsAtTimestamp(
	ctx_ context.Context,
	client_ graphql.Client,
	datetime int,
) (data_ *GetHistoricTickerStatsAtTimestampResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetHistoricTickerStatsAtTimestamp",
		Query:  GetHistoricTickerStatsAtTimestamp_Operation,
		Variables: &__GetHistoricTickerStatsAtTimestampInput{
			Datetime: datetime,
		},
	}

	data_ = &GetHistoricTickerStatsAtTimestampResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetPriceData.
const GetPriceData_Operation = `
query GetPriceData ($symbol: String!, $limit: Int!) {
	getHistoricPrice(symbol: $symbol, limit: $limit) {
		Pair {
			Symbol
			Price
		}
		Timestamp
	}
}
`

func GetPriceData(
	ctx_ context.Context,
	client_ graphql.Client,
	symbol string,
	limit int,
) (data_ *GetPriceDataResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetPriceData",
		Query:  GetPriceData_Operation,
		Variables: &__GetPriceDataInput{
			Symbol: symbol,
			Limit:  limit,
		},
	}

	data_ = &GetPriceDataResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetUserByEmail.
const GetUserByEmail_Operation = `
query GetUserByEmail ($email: String!) {
	getUserByEmail(email: $email) {
		id
		email
	}
}
`

func GetUserByEmail(
	ctx_ context.Context,
	client_ graphql.Client,
	email string,
) (data_ *GetUserByEmailResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetUserByEmail",
		Query:  GetUserByEmail_Operation,
		Variables: &__GetUserByEmailInput{
			Email: email,
		},
	}

	data_ = &GetUserByEmailResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
