name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs on every push to the main branch
  pull_request:
    branches:
      - main  # Runs on every PR to main

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub-hosted runner (free tier supports this)
    permissions:
      contents: read
      packages: write  # Needed if pushing to GitHub Container Registry (GHCR)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23  # Change to your Go version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Debug workspace
        run: ls -lah
        
     
      - name: Build & Push CBM Microservices
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: bazzamerx/cbmmicroservices:latest

      - name: Build & Push Resolvers
        uses: docker/build-push-action@v5
        with:
          context: ./Resolvers
          file: ./Resolvers/Dockerfile
          push: true
          platforms: linux/amd64
          tags: bazzamerx/cbmresolvers:latest